<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Rental extends Model
{
    protected $guarded = ['id'];

    protected $casts = [
        'waktu_mulai' => 'datetime',
        'waktu_selesai' => 'datetime',
        'completed_at' => 'datetime',
        'payment_details' => 'array',
    ];

    protected static function booted()
    {
        static::creating(function ($rental) {
            $rental->booking_code = self::generateUniqueBookingCode();
        });
    }

    private static function generateUniqueBookingCode()
    {
        do {
            $code = strtoupper(\Illuminate\Support\Str::random(12));
        } while (self::where('booking_code', $code)->exists());

        return $code;
    }

    public function units()
    {
        return $this->belongsToMany(Unit::class, 'rental_items')->withPivot('price_snapshot')->withTimestamps();
    }

    public function items()
    {
        return $this->hasMany(RentalItem::class);
    }

    /**
     * Get the affiliator associated with this rental.
     */
    public function affiliator(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(User::class, 'affiliator_id');
    }

    /**
     * Get the promo applied to this rental.
     */
    public function appliedPromo(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(PricingRule::class, 'applied_promo_id');
    }

    /**
     * Get the commissions generated by this rental.
     */
    public function commissions(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(AffiliateCommission::class);
    }
}
